// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CustomerOnb.Data
{
    public partial class State
    {
        public State()
        {
            Customer = new HashSet<Customer>();
            Lga = new HashSet<Lga>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public DateTime? CreatedDate { get; set; }

        public virtual ICollection<Customer> Customer { get; set; }
        public virtual ICollection<Lga> Lga { get; set; }
    }
}