// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CustomerOnb.Data
{
    public partial class TokenTable
    {
        public int Id { get; set; }
        public string Token { get; set; }
        public string PhoneNo { get; set; }
        public bool? IsUsed { get; set; }
        public DateTime? TokenGeneratedTime { get; set; }
        public DateTime? TokenExpiration { get; set; }
    }
}